version: '3.8'

volumes:
  pecodb_data:

services:
  tsumugi:
    build: 
      context: ./cbcc-services/cbcc-rest-api
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - ./cbcc-services/cbcc-rest-api:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@pecorine:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@pecorine:5432/api_test
    depends_on:
      - pecorine

  
  pecorine:
    build:
      context: ./cbcc-services/cbcc-db
      dockerfile: Dockerfile
    volumes:
      - pecodb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  kokkoro:
    stdin_open: true
    build:
      context: ./cbcc-services/cbcc-ui
      dockerfile: Dockerfile
    volumes:
      - './cbcc-services/cbcc-ui:/usr/src/app'
      - './usr/src/app/node_modules'
    ports:
    - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    depends_on:
      - tsumugi