"""boss icons should not be unique

Revision ID: 2b36daf8f650
Revises: ef67e15a87b8
Create Date: 2022-05-12 22:05:46.989582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b36daf8f650'
down_revision = 'ef67e15a87b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boss_icon_key', 'boss', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('boss_icon_key', 'boss', ['icon'])
    # ### end Alembic commands ###
