"""empty message

Revision ID: 3169684c243b
Revises: 
Create Date: 2022-05-11 18:15:43.981610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3169684c243b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=80), nullable=False),
    sa.Column('unit_name_en', sa.String(length=80), nullable=False),
    sa.Column('thematic', sa.String(length=80), nullable=True),
    sa.Column('thematic_en', sa.String(length=80), nullable=True),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('max_star', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_table('clan_battle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_battle_id', sa.Integer(), nullable=False),
    sa.Column('training_start_date', sa.DateTime(), nullable=False),
    sa.Column('training_end_date', sa.DateTime(), nullable=False),
    sa.Column('main_start_date', sa.DateTime(), nullable=False),
    sa.Column('main_end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_battle_id')
    )
    op.create_table('boss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=80), nullable=False),
    sa.Column('unit_name_en', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('clan_battle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_battle_id'], ['clan_battle.clan_battle_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boss')
    op.drop_table('clan_battle')
    op.drop_table('character')
    # ### end Alembic commands ###
