"""made ue nullable

Revision ID: 6e60c8e207e4
Revises: ac913ea07897
Create Date: 2022-05-16 13:31:49.768684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e60c8e207e4'
down_revision = 'ac913ea07897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_comp_character', 'ue',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_comp_character', 'ue',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
