"""empty message

Revision ID: ac913ea07897
Revises: 8239572d3045
Create Date: 2022-05-15 13:55:44.070013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac913ea07897'
down_revision = '8239572d3045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_comp_character', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_comp_character', 'level')
    # ### end Alembic commands ###
