name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build, Push and Deploy to Heroku
      id: heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Must be unique in Heroku
        email:  ${{ secrets.HEROKU_EMAIL }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile.deploy
        process_type: web
